---
version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - application
  application:
    container_name: app
    build: .
    environment:
    - FF_DB=${FF_DB}
    - FF_USER=${FF_USER}
    - FF_PASSWORD=${FF_PASSWORD}
    - FF_HOST=${FF_HOST}
    - FF_SECRET_KEY=${FF_SECRET_KEY}
...
