apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-app
  labels: 
    app: ff-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ff-app
  template:
    metadata:
      labels:
        app: ff-app
    spec:
      containers:
      - name: ff-app
        image: thebartthe/ff-app:5000
        env:
          - name: FF_USER
            value: ${FF_USER}
          - name: FF_PASSWORD
            value: ${FF_PASSWORD}
          - name: FF_DB
            value: ${FF_DB}
          - name: FF_HOST
            value: ${FF_HOST}
          - name: FF_SECRET_KEY
            value: ${FF_SECRET_KEY}
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: ff-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
