apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-app
  labels: 
    app: ff-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ff-app
  template:
    metadata:
      labels:
        app: ff-app
    spec:
      containers:
      - name: ff-app
        image: thebartthe/ff-app:5000
        env:
          - name: FF_USER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: user
          - name: FF_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
          - name: FF_DB
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: db
          - name: FF_HOST
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: host
          - name: FF_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: secretKey
     ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: ff-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
